In [0]:
import numpy
import pandas
from keras.models import Sequential, Model
from keras.layers import Dense, Input
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Making Preperation

In [0]:
from google.colab import files
uploaded = files.upload()

Saving housing.csv to housing (1).csv


In [0]:
# load dataset
dataframe = pandas.read_csv("housing.csv", delim_whitespace=True, header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:13]
Y = dataset[:,13]

# Creating a Baseline Model 


In [0]:
# define base model
def baseline_model():
  # create model
  model = Sequential()
  model.add(Dense(13, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(1))
  # Compile model
  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mse'])
  return model

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, epochs=100, batch_size=5, verbose=0)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))


W0826 10:23:03.889927 140475291551616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0826 10:23:03.956049 140475291551616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0826 10:23:03.967266 140475291551616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0826 10:23:04.008273 140475291551616 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0826 10:23:04.197901 140475291551616 deprecation_wrappe

Results: -42.63 (23.43) MSE


# Modeling the Standradised Dataset

In [0]:
# evaluate model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Standardized: -26.92 (32.54) MSE


In [0]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
mean = Y.mean(axis=0)
Y -= mean
std = Y.std(axis=0)
Y /= std

In [0]:
Y

array([ 0.15968566, -0.10152429,  1.32424667,  1.18275795,  1.48750288,
        0.6712218 ,  0.03996443,  0.49708184, -0.65659542, -0.39538548,
       -0.81985164, -0.39538548, -0.09064054, -0.23212926, -0.47157171,
       -0.286548  ,  0.06173193, -0.54775795, -0.25389676, -0.47157171,
       -0.97222411, -0.31919924, -0.79808414, -0.87427038, -0.75454915,
       -0.93957286, -0.64571167, -0.84161913, -0.44980422, -0.16682677,
       -1.07017784, -0.87427038, -1.0157591 , -1.02664285, -0.98310786,
       -0.39538548, -0.27566425, -0.16682677,  0.23587189,  0.89978051,
        1.34601416,  0.4426631 ,  0.30117438,  0.23587189, -0.14505928,
       -0.35185049, -0.27566425, -0.64571167, -0.88515413, -0.34096674,
       -0.30831549, -0.22124551,  0.26852314,  0.09438317, -0.39538548,
        1.4004329 ,  0.23587189,  0.98685049,  0.08349942, -0.31919924,
       -0.41715297, -0.71101416, -0.0362218 ,  0.26852314,  1.13922296,
        0.10526692, -0.34096674, -0.0579893 , -0.55864169, -0.17

In [0]:
# define base model
def baseline_model():
  # create model
  model = Sequential()
  model.add(Dense(13, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(1, activation = "sigmoid"))
  # Compile model
  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mse'])
  return model
# evaluate model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=baseline_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Standardized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Standardized: -0.64 (0.57) MSE


# Tuning the network Topology

# Evaluate a Deeper Network Topology

In [0]:
# define base model
def larger_model():
  # create model
  model = Sequential()
  model.add(Dense(13, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(6, activation="relu"))
  model.add(Dense(1))
  # Compile model
  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mse'])
  return model
# evaluate model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=larger_model, epochs=50, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Larger: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Larger: -22.58 (28.45) MSE


# Evaluate a wider network

In [0]:
# define base model
def wider_model():
  # create model
  model = Sequential()
  model.add(Dense(20, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(1))
  # Compile model
  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mse'])
  return model
# evaluate model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=wider_model, epochs=100, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Wider: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Wider: -21.11 (21.84) MSE


# Really Scaling up: developing a model that overfits

In [0]:
# define base model
def overfit_model():
  # create model
  model = Sequential()
  model.add(Dense(128, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(64, activation="relu"))
  model.add(Dense(32, activation="relu"))
  model.add(Dense(1))
  # Compile model
  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mse'])
  return model
# evaluate model with standardized dataset
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=overfit_model, epochs=200, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Overfits: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Overfits: -29.00 (21.85) MSE


# Optimized Model 

In [0]:
# define base model
def optimized_model():
  # create model
  model = Sequential()
  model.add(Dense(32, activation="relu", input_shape = (X.shape[1],)))
  model.add(Dense(1))
  # Compile model
  model.compile(optimizer='rmsprop',
                loss='mse',
                metrics=['mse'])
  return model
# evaluate model with standardized dataset
seed = 7
numpy.random.seed(seed)
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasRegressor(build_fn=optimized_model, epochs=75, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = KFold(n_splits=10, random_state=seed)
results = cross_val_score(pipeline, X, Y, cv=kfold)
print("Optimized: %.2f (%.2f) MSE" % (results.mean(), results.std()))

Optimized: -18.91 (22.10) MSE


In [0]:
results

array([ -8.99247942,  -6.30443755, -12.59054855, -25.03042662,
        -9.22693404,  -8.46041461,  -4.55317028, -83.04860716,
       -16.67859986, -14.18847297])

# Rewriting the code using the Keras Functional API

In [0]:
def create_funcAPI():
  inputs = Input(shape=(X.shape[1],))
  hidden = Dense(60, activation = "relu")(inputs)
  hidden = Dense(30, activation = "relu")(hidden)
  hidden = Dense(15, activation = "relu")(hidden)
  prediction = Dense(1)(hidden)
  model = Model(inputs = inputs, outputs = prediction)
  model.compile(loss = "mse",
                optimizer = "rmsprop",
                metrics = ["mse"]
  )
  return model

# Rewriting the code by doing Model Subclassing

In [0]:
class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    #Define the layers
    inputs = Input(shape=(X.shape[1],))
    self.dense_1 = Dense(32, activation= "relu")
    self.dense_2 = Dense(1)
  def call(self, inputs):
    # Define your forward pass here,
    # using layers you previously defined in `__init__`
    x = self.dense_1(inputs)
    return self.dense_2(x)
def model_subclass():
  model = MyModel()

  #compiling the model
  model.compile(optimizer='rmsprop',
                loss='mse',
                metrics=['mae'])
  return model


# Evaliuation without using Scikit-Learn

In [0]:
k = 5
num_val_samples = len(X)//k
all_scores = []

for i in range(k):
  print("Processing fold #", i )
  val_X = X[i * num_val_samples : (i+1) * num_val_samples]
  val_Y = Y[i* num_val_samples : (i+1) * num_val_samples]
  
  partial_X = numpy.concatenate(
  [X[:i * num_val_samples],
  X[(i+1)* num_val_samples : ]]
  , axis = 0)
  
  partial_Y = numpy.concatenate(
  [Y[:i * num_val_samples],
  Y[(i+1)* num_val_samples : ]]
  , axis = 0)
  
  model = model_subclass()
  model.fit(partial_X, partial_Y, epochs = 75, batch_size = 5, verbose= 0)
  val_mse, val_mae = model.evaluate(val_X, val_Y, verbose=0)
  all_scores.append(val_mse)
  

Processing fold # 0
Processing fold # 1
Processing fold # 2
Processing fold # 3
Processing fold # 4


In [0]:
print("Standardized: %.2f (%.2f)" % (numpy.mean(all_scores), numpy.std(all_scores)))


Standardized: 38.96 (13.58)
